services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 8070:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - 8071:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data/db
    env_file:
      - ./backend/.env.production

volumes:
  mongo_data: